<div id="devtool-events">
    <?php foreach ($this->getEvents() as $event): ?>
        <h3><a href="#"><?php echo $event->getName() ?></a></h3>
        <div class="devtool-event">
            <ul>
                <li><a href="#tabs-<?php echo $event->getName() ?>-params">Params</a></li>
                <li><a href="#tabs-<?php echo $event->getName() ?>-attach-xml">Attach XML</a></li>
            </ul>
            <div id="tabs-<?php echo $event->getName() ?>-params">
                <?php echo Mage::helper('devtool')->printr($event->getParams(), true) ?>
            </div>
            <div id="tabs-<?php echo $event->getName() ?>-attach-xml">
                <pre>
&lt;global&gt;
    &lt;events&gt;
        &lt;<?php echo $event->getName() ?>&gt;
            &lt;observers&gt;
                &lt;my_observer&gt;
                    &lt;type&gt;singleton&lt;/type&gt;
                    &lt;class&gt;{{MODULE_NAME}}/{{MODEL_NAME}}&lt;/class&gt;
                    &lt;method&gt;{{METHOD_NAME}}&lt;/method&gt;
                &lt;/my_observer&gt;
            &lt;/observers&gt;
        &lt;/<?php echo $event->getName() ?>&gt;
    &lt;/events&gt;
&lt;/global&gt;
                </pre>
            </div>
            <script type="text/javascript">
                <!--
                jQuery(document).ready(function(){
                    jQuery('.devtool-event').tabs()
                });
                //-->
            </script>
        </div>
    <?php endforeach; ?>
</div>
<script type="text/javascript">
<!--
jQuery(document).ready(function(){
    jQuery('#devtool-events').accordion({
        cookie: true,
        collapsible: true,
        active: false
    })
});
//-->
</script>