<?php if (true == $this->showDevtool()): ?>
<div id="devtool-main">
    <div id="devtool-tabs">
        <ul>
            <li id="devtool-caption">Magento Devtool</li>
            <?php foreach ($this->getSortedChildBlocks() as $key => $child): ?>
                <li><a href="#tabs-<?php echo $key?>"><?php echo $child->getBlockAlias() ?></a></li>
            <?php endforeach; ?>
        </ul>
        <?php foreach ($this->getSortedChildBlocks() as $key => $child): ?>
            <div id="tabs-<?php echo $key?>">
                <?php echo $child->toHtml() ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<script type="text/javascript">
<!--
jQuery(document).ready(function(){
    // Tabs
    jQuery('#devtool-tabs')
        .tabs({
            collapsible: true,
            selected: -1
        })
        .find(".ui-tabs-nav" ).sortable({ axis: "x" });
});
//-->
</script>
<?php endif; ?>