<?php if ($this->isRegistryEnabled()): ?>
<div id="devtool-registry" class='devtool-tab-view'>
    <ul>
        <li><a href="#tabs-registry-others"><?php echo $this->__('Others')?></a></li>
        <li><a href="#tabs-registry-singletons"><?php echo $this->__('Singletons')?></a></li>
        <li><a href="#tabs-registry-helper"><?php echo $this->__('Helper')?></a></li>
        <li><a href="#tabs-registry-all"><?php echo $this->__('All')?></a></li>
    </ul>
    <div id="tabs-registry-others" class="devtool-tree-view">
        <?php echo Mage::helper('devtool')->printr($this->getOthers(), true)?>
    </div>
    <div id="tabs-registry-singletons" class="devtool-tree-view">
        <?php echo Mage::helper('devtool')->printr($this->getSingletons(), true)?>
    </div>
    <div id="tabs-registry-helper" class="devtool-tree-view">
        <?php echo Mage::helper('devtool')->printr($this->getHelpers(), true)?>
    </div>
    <div id="tabs-registry-all" class="devtool-tree-view">
        <?php echo Mage::helper('devtool')->printr($this->getRegistry(), true)?>
    </div>
</div>
<?php else: ?>
<div id="devtool-registry" class='devtool-tab-view'>
    <p><?php echo $this->__('There is no function getRegistry() available in class Mage. If you want to use this functionality add the following method to class Mage in app/Mage.php:') ?></p>
    <pre>
        /**
         * Returns current registry array
         * 
         * @return array
         */
        public static function getRegistry()
        {
            return self::$_registry;
        }
    </pre>
</div>
<?php endif;?>